apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: woocommerce-cluster
  region: us-east-1
  version: "1.33"

vpc:
  id: "vpc-02680e5ab48377db7"
  subnets:
    public:
      us-east-1a:
        id: subnet-047097a493cd4831a
      us-east-1b:
        id: subnet-074b259b6e93f5315
      us-east-1c:
        id: subnet-0ff7ac635b710ae85
      us-east-1d:
        id: subnet-0584f388ca671c05b
      us-east-1e:
        id: subnet-0b462a318d4ff5e26
      us-east-1f:
        id: subnet-039ebfae92e83d83f

iam:
  withOIDC: true

nodeGroups:
  - name: ng-t3-medium
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    privateNetworking: false
    ssh:
      allow: true
      publicKeyName: eks-ec2-key-pair
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSAutoClusterPolicy
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess

addons:
  - name: vpc-cni
    version: latest
    podIdentityAssociations:
      - serviceAccountName: aws-node
        namespace: kube-system
        roleARN: arn:aws:iam::992382421164:role/AmazonEKSVPCCNIRole

  - name: kube-proxy
    version: latest

  - name: coredns
    version: latest

  - name: metrics-server
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  - name: eks-pod-identity-agent
    version: latest
