apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: backend-service-account
      containers:
      - name: gateway
        image: 992382421164.dkr.ecr.us-east-1.amazonaws.com/nginx_gateway_ssl:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: DOMAIN
          value: "inventory.caotienminh.software"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: web-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-047097a493cd4831a,subnet-0ff7ac635b710ae85,subnet-0584f388ca671c05b,subnet-0b462a318d4ff5e26,subnet-074b259b6e93f5315,subnet-039ebfae92e83d83f"
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
